config/routes.rb
Genpop::Application.routes.draw do
  resources :users
  
  get "welcome/index"
  
  match "signup", to: "users#new", via: "get"
  

   root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
##
# Controller for User objects. Handles routing for the following:
# - Registration
# - Directory Listing
# - Directory Search [possibly]
# - Viewing User Profiles
# - Editing User Information
# - Deleting Users
class UsersController < ApplicationController
  def new
  end

  ##
  # Saves a new User submitted through the signup form in #new
  def create
    data = params.require(:user).permit(:name, :username, :email)
    @user = User.new(data)
    @user.save
    redirect_to @user
  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
  end

  ##
  # Displays a single user
  def show
    @user = User.find(params[:id])
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
##
# Controller for static pages
class WelcomeController < ApplicationController

  ##
  # Site Index
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
##
# Provides utilities for displaying Users
module UsersHelper

  ##
  # Returns a gravatar url for a user
  def gravatar_url(user,size=50,d="identicon")
    id = Digest::MD5::hexdigest user.email.downcase
    return "https://secure.gravatar.com/avatar/#{id}?s=#{size}&d=#{d}"
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bismillah - GenPop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-th-list"></span>
				</a>
				<a href="#" class="brand">GenPop</a>
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#">Help</a></li>
						<li><a href="#">Sign In</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<%= yield %>
</div>
</body>
</html>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |u| %>
	<div class="media">
		<a class="pull-left" href="#">
			<img class="media-object" src="<%= gravatar_url u, 48 %>" alt="<%= u.username %>">
		</a>
		<div class="media-body">
			<h4 class="media-heading"><%= u.name %></h4>
			<em><%= u.username %></em>
			<span class="glyphicon glyphicon-envelope"></span> <%= u.email %>
			
		</div>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div>
	<%= form_for :user, url: users_path do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.submit "Create Account", :class => "btn btn-success" %>
	</p>
	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<em>username:</em>&nbsp;<%= @user.username %><br>
<em>email:</em>&nbsp;<%= @user.email %><br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="hero-unit">
	<div class="container">
		<h1>Bismillah</h1>
		<p>This is the GenPop homepage!</p>
		<p><a href="signup" class="btn btn-success btn-lg">Sign Up Now!</a></p>
	</div>
</div>